name: mindgum
favicon: null
layout_spectrum: 0.04488
typography_spectrum: 0.54773
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#2f2f2f'
    - '#dcdcdc'
    - '#959595'
  brandStrength: 0.5
  lightness: 0.25
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
